spring:
  application:
    name: content-generator
  main:
    banner-mode: off
  data:
    mongodb:
      host: localhost
      port: 27017
      database: content-generator
      auto-index-creation: true
  ai:
    mcp:
      server:
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
        name: webflux-mcp-server
        version: 1.0.0
        type: SYNC
        sse-message-endpoint: /mcp/messages

logging:
  file:
    name: ./target/logs/content-generator.log